### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by Fire-Star** [xuxiaoxiao-xxx/ChatApi-QQ#2]
大佬，测试后发现登录成功后出现空指针异常。

异常信息：
【
登录成功
sendFriend
friendId:
1428384239
content:
sdf
Exception in thread "main" java.lang.NullPointerException
	at me.xuxiaoxiao.chatapi.qq.QQClient.sendText(QQClient.java:178)
	at main.WebQQTest.main(WebQQTest.java:62)
9月 12, 2018 12:53:39 上午 me.xuxiaoxiao.chatapi.qq.QQClient$QQThread listen
较详细: 暂无信息
】

**Comment by xuxiaoxiao-xxx** [comment]
发送消息时，参数friendId，并不是好友的qq号。这个id可以等好友向你发送消息时，通过debug获取

**Comment by Fire-Star** [comment]
好，谢谢大佬。我最近几天学校这边办理入学手续，没有及时回复，有点抱歉。
